config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :articles
  devise_for :users
  root "pages#show", page: "home"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true

  has_one_attached :image
  belongs_to :category
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password)}
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
        end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @first_article = Article.first
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :image, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :priority)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
      @categories = Category.all
      @articles = Article.all

      @first_article = Article.first
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control-file' %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.map{ |c| [c.name, c.id]} %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="mx-auto" style="width:80%; height: auto">
      <div class="col-lg-12 mx-auto">
        <div class="mt-4">
          <%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
        </div>
        <p id="notice"><%= notice %></p>
        <h1>Articles</h1>

        <% @articles.each do |article| %>

        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title"><%= link_to article.title, article %></h2>
            <p>Posted on <%= article.created_at %></p>
            <div class="article-body">
              <%= image_tag(article.image, style: "width:200px") %>
              <p class="card-text pl-5"><%= truncate(article.description, length: 350) %></p>
            </div>
          </div>
          <div class="card-footer text-muted">

            <%= link_to 'Show', article, class: 'card-link' %>
            <%= link_to 'Edit', edit_article_path(article), class: 'card-link' %>
            <%= link_to 'Destroy', article, class: 'card-link', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="mx-auto" style="width:80%; height: auto">
      <div class="col-lg-8 mx-auto">
        <h1>New Article</h1>

        <%= render 'form', article: @article %>
      </div>

      <div class="col-lg-8 mx-auto">
        <%= link_to 'Back', articles_path %>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="mx-auto" style="width:80%; height: auto">
        <div class="col-lg-12">
          <%= image_tag(@article.image, style: "width:100%" ) %>
          <div class="container text-center">
            <p class="lead">Category: <%= @article.category.name %></p>
             <h1><%= @article.title %></h1>
             <p class="text-muted">Posted by <%= current_user.email %> at <%= @article.created_at %></p>
           </div>
        </div>
      </div>

      <div class="col-lg-8 mx-auto">
        <p><%= @article.description %></p>
      </div>

      <div class="col-lg-8 mx-auto">
        <% if current_user %>
        <%= link_to 'Edit', edit_article_path(@article) %> |
        <%= link_to 'Back', articles_path %>
        <% else %>
            <%= link_to 'Rate Article', "#" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <%= form.number_field :priority, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="mx-auto" style="width:80%; height: auto">
      <div class="col-lg-8 mx-auto">
        <h1>Editing Category</h1>

        <%= render 'form', category: @category %>
      </div>

      <div class="col-lg-8 mx-auto">
        <%= link_to 'Show', @category %> |
        <%= link_to 'Back', categories_path %>
      </div>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="mx-auto" style="width:80%; height: auto">
      <div class="col-lg-8 mx-auto">
        <p id="notice"><%= notice %></p>

        <h1>Categories</h1>

        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Priority</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.priority %></td>
                <td><%= link_to 'Show', category %></td>
                <td><%= link_to 'Edit', edit_category_path(category) %></td>
                <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-lg-8 mx-auto">
        <%= link_to 'New Category', new_category_path %>
      </div>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<div class="container">
    <div class="row align-items-center mt-5">
        <div class="col-4">
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                  <h1>Add a Category</h1>

                  <%= render 'form', category: @category %>

                  <%= link_to 'Back', categories_path %>

                </div>
            </div>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="mx-auto" style="width:80%; height: auto">
      <div class="col-lg-8 mx-auto">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @category.name %>
        </p>

        <p>
          <strong>Priority:</strong>
          <%= @category.priority %>
        </p>
      </div>

      <div class="col-lg-8 mx-auto">
        <%= link_to 'Edit', edit_category_path(@category) %> |
        <%= link_to 'Back', categories_path %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifestylePark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/cbc2432238.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) || current_page?(edit_user_registration_path) %>
      <%= render 'shared/navbar'  %>
    <% end %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render 'shared/footer'  %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <%= image_tag(@first_article.image, class: "intro-img img-fluid mb-3 mb-lg-0 rounded" ) %>
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4">
          <span class="section-heading-upper"><%= @first_article.category.name %></span>
        </h2>
        <h2><%= @first_article.title %></h2>
        <p class="mb-3"><%= truncate(@first_article.description, length: 250) %></p>

      </div>
    </div>
  </div>
</section>

<section class="category_section">
  <div class="container">
    <div class="row">
      <% @articles.each do |article|%>
      <div class="col-lg 3 col-md-3 col-sm-12 col-xs-12 mt-4">
        <div class="card shadow-sm">
          <div class="overlay-effect h-100 w-100"></div>
          <%= image_tag(article.image, class: "img-fill" ) %>
          <div class="card-body">
            <div class="card-body-header">
              <h6 class="card-subtitle mb-2"><%= article.category.name %></h6>
            </div>
            <div class="card-body-footer">
              <h4 class="card-text"><%= link_to article.title,  article_path(article.id)%></h4>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

<section class="articles_section mt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <% @articles.each do |article|%>
        <div class="post-preview">
          <div class="img-card">
            <h3 class="post-title"><%= link_to article.title,  article_path(article.id)%></h3>
            <h6 class="post-scategory"><%= article.category.name %></h6>
            <p class="post-meta">Posted on September 24, 2019</p>
          </div>
          <div class="post-card">
            <div class="post-img">
              <%= image_tag(article.image, class: "thumbnail" ) %>
            </div>
            <p class="post-meta"><%= truncate(article.description, length: 400) %></p>
          </div>
        </div>
        <hr>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="footer bg-dark">
  <div class="container">
    <span class="text-muted">Lifestyle Park</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Lifestyle Park",root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <p class="navbar-text float-right">

        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fas fa-search"></i> Search
          </a>
        </li>
      <% if user_signed_in? %>

      <li class="nav-item">
          <%= link_to 'Write an Article', new_article_path, class: 'nav-link'%>

      </li>

      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-dark'  %>
      </li>
      <% else %>


      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link btn btn-dark'  %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-outline-light'  %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>